# See https://spark.gameforge.com/api/v1/product/ for game list, "gameInternalName" is the game name
# See https://spark.gameforge.com/api/v1/patching/download/branches/${gameInternalName} for branchs list

# skip sha1 validation, better to keep this to false
skip_hash = false

# oh no gameforge u did it again, something unreleased is public on your servers :|
[[games]]
name = "aionclassic"
branch = "default"
output = "./games/aionclassic/default"
sandbox = true

# [[games]]
# name = "aion"
# branch = "default"
# output = "./games/aion/default"
# sandbox = true
