name: Publish

on: [push]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Copy exe
        run: Copy-Item -Path target/release/gf-client-game-updater.exe -Destination gf-client-game-updater.exe

      - uses: actions/upload-artifact@v2
        with:
          name: gf-client-game-updater
          path: |
            gf-client-game-updater.exe
            config.toml
